# SPDX-License-Identifier: GPL-2.0-only

KBUILD_DEFCONFIG := linxisa_virt_defconfig

UTS_MACHINE := linx64

# Avoid generating .eh_frame sections.
KBUILD_CFLAGS += -fno-asynchronous-unwind-tables -fno-unwind-tables

